arm/base:
  type: effort_controllers/JointPositionController
  joint: plate_joint
  pid:
    p: 1000.0
    i: 50.0
    d: 150.0

arm/j1:
  type: effort_controllers/JointPositionController
  joint: j1_joint
  pid:
    p: 1000.0
    i: 50.0
    d: 150.0

arm/j2:
  type: effort_controllers/JointPositionController
  joint: j2_joint
  pid:
    p: 1000.0
    i: 50.0
    d: 150.0

arm/j3:
  type: effort_controllers/JointPositionController
  joint: j3_joint
  pid:
    p: 1000.0
    i: 50.0
    d: 150.0

arm/j4:
  type: effort_controllers/JointPositionController
  joint: j4_joint
  pid:
    p: 1000.0
    i: 50.0
    d: 150.0
arm/f1:
  type: effort_controllers/JointPositionController
  joint: f1_joint
  pid:
    p: 1.0
    i: 0.0
    d: 0.1
arm/f2:
  type: effort_controllers/JointPositionController
  joint: f2_joint
  pid:
    p: 1.0
    i: 0.0
    d: 0.1

rot:
  type: effort_controllers/JointPositionController
  joint: rot_joint
  pid:
    p: 50.0
    i: 0.0
    d: 5.0

cam_y:
  type: effort_controllers/JointPositionController
  joint: cam_yaw_joint
  pid:
    p: 50.0
    i: 0.0
    d: 5.0

shovel:
  type: effort_controllers/JointPositionController
  joint: shovel_joint
  pid:
    p: 30.0
    i: 0.0
    d: 0.8

roller/arm:
  type: effort_controllers/JointPositionController
  joint: roller_arm_joint
  pid:
    p: 200.0
    i: 0.0
    d: 5.0

roller/slider:
  type: effort_controllers/JointPositionController
  joint: roller_arm_slider
  pid:
    p: 50.0
    i: 1.0
    d: 1.5




